### PR TITLE
Milestone 2 - User Interface Ruby #4 project

### PR DESCRIPTION
**Pull request by Jaakal**
Created all the necessary print out functions and inputs and set up one dummy iteration of the coming game.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi Jaakal!

### Nice job! Project looks! :+1: 

But first of all let's fix the next problems and we can move on.


## `[OPTIONAL]` 
* game ask players for their names. As I can see, now in your game asking about the name but only "Player one..."

##  `[REQUIRED]` : 
* game tells which player turn it is
* game asks player to select from available moves
* game informs player if selected move is invalid
* game displays board after player move
* game informs player if selected move is a winning move
* game informs player if selected move is a draw move
* game repeats all actions for next player's move

##### Implementation details

*  A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* Inside loop should all actions repeated for each move
* A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:



### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes

**Review by uche-inyama — APPROVED** [review]
## Approved

Hi Jaakal!

Go ahead with next milestone.  Ensure to take note of the points listed by my colleague - Anna, while working on the next milestone. :slightly_smiling_face: 

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama```

**Pull request merged**
